import Head from 'next/head';
import React from 'react'


const About = () => {
  return <>
    <Head>
      <title>About Me | Anshul</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>About</div>
    </>
}

export default About;