import Head from 'next/head';
import React from 'react'

const Blogs = () => {
  return <>
    <Head>
      <title>Blogs | Anshul</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>Blogs</div>
  </>
}

export default Blogs;